version: "3.8"

services:
  sentiment_analysis:
    build: ./services/sentiment_analysis
    container_name: sentiment_analysis
    ports:
      - "8001:80" 
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}

  summarization:
    build: ./services/summarization
    container_name: summarization
    ports:
      - "8002:80" 
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}